### ISSUE TITLE
Analysis: Mis-registered file uploads from Ingest UI uploads

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/uuid-api#102]
Check all `INGEST_PORTAL_UPLOAD` file registrations:
  - Do the files exist on the file system (if not what is the list of non-existent files by ancestor id?)
  - Do the ancestors/parents of missing files exist in Neo4j and are the files listed in these records?

**Comment by kburke** [comment]
Of 96 "ancestor" UUIDs which for files missing on the file system, 93 of those ancestors existing in Neo4j.
Cypher queries attached.  Next I try looking at files on their records
[AncestorsWithMissingFiles.cypher.txt](https://github.com/hubmapconsortium/uuid-api/files/9135482/AncestorsWithMissingFiles.cypher.txt)
[AncestorsWithMissingFilesWhoAreMissingThemselves.cypher.txt](https://github.com/hubmapconsortium/uuid-api/files/9135483/AncestorsWithMissingFilesWhoAreMissingThemselves.cypher.txt)
.

**Comment by kburke** [comment]
Did a file export of the Production database to my laptop about 10:15 this morning.  Then executed commands in this file
[RemediationQueries_Production_20220720.sql.txt](https://github.com/hubmapconsortium/uuid-api/files/9152607/RemediationQueries_Production_20220720.sql.txt)
