### ISSUE TITLE
Support for `Publication` entities

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/uuid-api#121]
The new [Publication entities](https://github.com/hubmapconsortium/entity-api/issues/439) are a subclass of `Datasets` and as such, can have Files associated with them.

My thought is that we register `Publication` entities as ENTITY_TYPE `Dataset` because the UUID service is not meant as a service to look up entities, rather as a service to generate and look up ids.  We could add a new column ENTITY_SUB_TYPE that would get set to Publication..

@kburke let's discuss this

**Comment by kburke** [comment]
Added a column to hold JSON describing the class of an entity with the following SQL query:
```
ALTER TABLE `hm_uuid`.`uuids_attributes` 
ADD COLUMN `ENTITY_CLASS_METADATA` JSON NULL AFTER `DESCENDANT_COUNT`;
```
For a "Publication-class DATASET", this column will contain:
`{"class": "Publication"}`
Modified MySQL Workbench model, ER diagram PDF, and DDL in the `sql` directory with these changes, as well.
Change `*.cfg.example` files and `uuid_worker.py` to support entity classes and to constrain accepted entities to known types.

**Comment by kburke** [comment]
No new support reading, updating, or deleting related to "entity class".  All DATASET relationships (business rules) apply to "Publication-class" DATASETs.
