### ISSUE TITLE
Querying file information given dataset UUID

### ISSUE THREAD

**Issue by icaoberg** [hubmapconsortium/uuid-api#44]
From my understanding, I can query the DB given a valid UUID.

Since I will be using the API to create UUIDs and store checksums at the file level, I think it would be useful to have a query method such that given a dataset UUID, I can retrieve all the files associated with the dataset. 

For example, given the query body

```
{parent_ids": ["517539cee7b8ea5909150998f5486a17"]}
```

the response would be something like

```
"file_info": [
        {
           "uuid":"this-is-the-uuid-generated-by-the-api"
            "path": "WGS-metadata.tsv",
            "size": 1041,
            "checksum": "46726de4d2af0af2b4335fd3b35df200",
            "base_dir": "DATA_UPLOAD"
        }

        ..........
    ]
```

**Comment by shirey** [comment]
@icaoberg We can do this. Instead of passing the dataset uuid in via a json payload, we'll do it like this:
GET `https://uuid.api.hubmapcosortium.org/<uuid>/files`

**Comment by shirey** [comment]
@icaoberg this is finished and being released today maybe?(@yuanzhou ).  It is documented in the code here (and SmartAPI once released) https://github.com/hubmapconsortium/uuid-api/blob/50d2594502d662d8a51780ad8fa818bf3c135234/src/app.py#L223-L278
