### ISSUE TITLE
File uuid info by parent-entity broken

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/uuid-api#68]
On DEV the following call should return information about all files attached to dataset `4081680ef553db5f91fb3587dde595b6`.

Instead a 500 is returned with the message "Unexpected error: 'UUIDWorker' object has no attribute 'get_file_info'"

`https://uuid-api.dev.hubmapconsortium.org/4081680ef553db5f91fb3587dde595b6/files`

**Comment by maxsibilla** [comment]
Issue has been resolved and fix is on test-release
