### ISSUE TITLE
Support app-specific globus-groups.json in app.cfg

### ISSUE THREAD

**Issue by kburke** [hubmapconsortium/uuid-api#80]
Replace the current GLOBUS_GROUPS boolean in app.cfg, used to specify whether to override Globus groups information.  Switch to GLOBUS_GROUPS_FILENAME, specifying an app-specific JSON file in the instance directory when override is desired, and the Python value None when override is not desired.

Leave the existing instance/globus-groups.json in the Git repo.  Modify app.cfg.example and sennet.app.cfg.example to support the configuration change, with the understanding the app-specific configuration will always be deployed with the name 'app.cfg' in the instance directory.

**Comment by kburke** [comment]
Following discussion with @yuanzhou and @shirey revising this card from initial write-up.  Please confirm current revision reflects task compared with what was stated below, particularly re: Bill's direction to remove globus-groups.json from repo:

### Remove globus-groups.json from Git repo #80

"app.py contains code to load Globus Groups settings from a JSON file under /instance, based on the setting GLOBUS_GROUPS in app.cfg. Bill would like the JSON file removed from the Git repo and the code cleaned up.

The GROUPS info file to be used should be specified in the app.cfg of the associated service/application and passed to the hubmap-commons group utility/worker at instantiation. Locating the GROUPS info file in the src/instance/ directory alongside app.cfg seems like the appropriate place for it, but ignored by git as app.cfg is."

**Comment by shirey** [comment]
@kburke @yuanzhou For now leave the globus_groups.json, as is, checked into GitHub.  Another issue will be coming to replace both the reference to a group info file to a central repo and to only use the `commons` package to retrieve group information.
