### ISSUE TITLE
Add default UUID prefix for file registrations

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/uuid-api#91]
Via a configuration item `file_uuid_prefix` that specifies a 4 digit hexadecimal number which will be used to constrain all registered FILE uuids to start with those 4 digits and all other entity types to be excluded from those 4 digits.

**Comment by kburke** [comment]
@shirey Are you sure you want this as a configuration file item, that the apps can change or that can go unnoticed if it is misconfigured a while during data creation?  I don't like hard-coding what may need changing, but I thought this would be better in an enumeration inside uuid_worker.py.
