### ISSUE TITLE
Pick a hex prefix for FILE UUID registrations and convert existing FILE UUIDs to use it.

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/uuid-api#92]
This is dependent on completion of #91 first.

Chose a 4 digit hex prefix for all FILE registration UUIDs (see #91).  Currently it looks like `ffff` will work.

The existing UUID (MySQL) and Entity API (Neo4j) databases along with directories on the `hive` file system contain several file registrations.  Convert these UUIDs (change in databases and on `/hive/` file system to start with the chosen prefixes.

**Comment by kburke** [comment]
Can you direct me to how the UUID associated with FILE entity_types is manifest in the PSC file system?
When I look at /hive/hubmap/data/public, I see files underneath directories, but I do not see the FILE UUID in the directory or file **_names_**.
I did not search **_inside_** all the files, but I'm not seeing any kind of consistent manifest file that might contain all the FILE UUIDs underneath the SAMPLE directory.
We only had data for 492 files in the database dump from the end of May.  Maybe these align with something in the protected or the consortium directories, which I cannot see?
Just trying to get some scripts ready...

**Comment by kburke** [comment]
@shirey Thanks for point out the need to modify PATH.  I missed that, but it was simple modification.  I do have a Python script sitting at the PSC which will work with a CSV file from a crosswalk table for FILE UUIDs that I create when I create a V2 database from a V1 source.  It is interesting to see where the gaps are in /hive/hubmap/assets and on PATH entries starting with /hubmap-data/hm_uploads/.  We can coordinate who does when planning the migration with Joe...might want you to spend that 10 minutes on Neo4J!
