### ISSUE TITLE
Performance testing with extended FILE data

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/uuid-api#93]

**Comment by kburke** [comment]
Discussed [Google Doc ](https://docs.google.com/document/d/1kmcXKWvDoJNv1MlQL5U08g9ynFWHPbT6c4-DWtDLIw0/edit?usp=sharing) contents with John Milnes and Bill.  Aware of possible degradation of write performance as the database grows, but ready to move on with deployment.
